[variables]
# Configura el directorio público para Nginx
NIXPACKS_PHP_ROOT_DIR = "/app/public"

[phases.build]
# Se ejecuta durante la construcción de la imagen en Railway
cmds = [
    "npm run build",
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs bootstrap/cache",
    "chmod -R 777 storage bootstrap/cache"
]
